# Generated by Django 5.0.2 on 2025-06-09 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='+237600000000', help_text='Example: +237612345678', max_length=15, validators=[django.core.validators.RegexValidator('^\\+237[6-7][0-9]{7}$', message='Enter a valid Cameroonian phone number starting with +237')]),
        ),
    ]
