# Generated by Django 5.0.2 on 2025-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CHECKING', 'Checking Account'), ('FIXED', 'Fixed Deposit Account'), ('LOAN', 'Loan Account'), ('CREDIT', 'Credit Account'), ('MOBILE', 'Mobile Money Account'), ('VIRTUAL', 'Virtual Account'), ('BUSINESS', 'Business Account'), ('JOINT', 'Joint Account'), ('STUDENT', 'Student Account'), ('RETIREMENT', 'Retirement Account'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
