# Generated by Django 5.0.2 on 2025-06-10 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='+237600000000', help_text='Example: +237677202148', max_length=15, validators=[django.core.validators.RegexValidator('^\\+237[6][0-9]{8}$', message='Enter a valid Cameroonian phone number starting with +237')]),
        ),
    ]
